// Code generated by qtc from "create_table.sql.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line create_table.sql.qtpl:1
package migration

//line create_table.sql.qtpl:1
import (
	infoblog "gitlab.com/InfoBlogFriends/server"
)

//line create_table.sql.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line create_table.sql.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line create_table.sql.qtpl:5
func StreamCreateTable(qw422016 *qt422016.Writer, table infoblog.Table) {
//line create_table.sql.qtpl:5
	qw422016.N().S(`
create table `)
//line create_table.sql.qtpl:6
	qw422016.E().S(table.Name)
//line create_table.sql.qtpl:6
	qw422016.N().S(`
(
	`)
//line create_table.sql.qtpl:8
	for i, field := range table.Fields {
//line create_table.sql.qtpl:8
		qw422016.N().S(`
        `)
//line create_table.sql.qtpl:9
		qw422016.E().S(field.Name)
//line create_table.sql.qtpl:9
		qw422016.N().S(` `)
//line create_table.sql.qtpl:9
		qw422016.E().S(field.Type)
//line create_table.sql.qtpl:9
		qw422016.N().S(` `)
//line create_table.sql.qtpl:9
		if field.Default == "" {
//line create_table.sql.qtpl:9
			qw422016.N().S(`null`)
//line create_table.sql.qtpl:9
		}
//line create_table.sql.qtpl:9
		qw422016.E().S(field.Default)
//line create_table.sql.qtpl:9
		qw422016.N().S(` `)
//line create_table.sql.qtpl:9
		if len(table.Fields) != i+1 {
//line create_table.sql.qtpl:9
			qw422016.N().S(`,`)
//line create_table.sql.qtpl:9
		}
//line create_table.sql.qtpl:9
		qw422016.N().S(`
	`)
//line create_table.sql.qtpl:10
	}
//line create_table.sql.qtpl:10
	qw422016.N().S(`
);

`)
//line create_table.sql.qtpl:13
	if len(table.Constraints) > 0 {
//line create_table.sql.qtpl:13
		qw422016.N().S(`
    `)
//line create_table.sql.qtpl:14
		for _, constraint := range table.Constraints {
//line create_table.sql.qtpl:14
			qw422016.N().S(`
    create `)
//line create_table.sql.qtpl:15
			if constraint.Unique {
//line create_table.sql.qtpl:15
				qw422016.N().S(`unique `)
//line create_table.sql.qtpl:15
			}
//line create_table.sql.qtpl:15
			qw422016.N().S(`index `)
//line create_table.sql.qtpl:15
			qw422016.E().S(table.Name)
//line create_table.sql.qtpl:15
			qw422016.N().S(`_`)
//line create_table.sql.qtpl:15
			qw422016.E().S(constraint.FieldName)
//line create_table.sql.qtpl:15
			qw422016.N().S(`_idx
     on `)
//line create_table.sql.qtpl:16
			qw422016.E().S(table.Name)
//line create_table.sql.qtpl:16
			qw422016.N().S(` (`)
//line create_table.sql.qtpl:16
			qw422016.E().S(constraint.FieldName)
//line create_table.sql.qtpl:16
			qw422016.N().S(`);`)
//line create_table.sql.qtpl:16
		}
//line create_table.sql.qtpl:16
		qw422016.N().S(`
`)
//line create_table.sql.qtpl:17
	}
//line create_table.sql.qtpl:17
	qw422016.N().S(`
     `)
//line create_table.sql.qtpl:18
	qw422016.E().S(table.Entity.OnCreate())
//line create_table.sql.qtpl:18
}

//line create_table.sql.qtpl:18
func WriteCreateTable(qq422016 qtio422016.Writer, table infoblog.Table) {
//line create_table.sql.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line create_table.sql.qtpl:18
	StreamCreateTable(qw422016, table)
//line create_table.sql.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line create_table.sql.qtpl:18
}

//line create_table.sql.qtpl:18
func CreateTable(table infoblog.Table) string {
//line create_table.sql.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line create_table.sql.qtpl:18
	WriteCreateTable(qb422016, table)
//line create_table.sql.qtpl:18
	qs422016 := string(qb422016.B)
//line create_table.sql.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line create_table.sql.qtpl:18
	return qs422016
//line create_table.sql.qtpl:18
}
