run:
  concurrency: 4 # default concurrency is a available CPU number
  timeout: 30s # timeout for analysis, e.g. 30s, 5m, default is 1m
  issues-exit-code: 1 # exit code when at least one issue was found, default is 1
  tests: true # include test files or not, default is true
  skip-dirs:
    - docs