version: '3.3'
services:
  api:
    container_name: "infoblogserver"
    build: "."
    command: bash -c "go run ./cmd/server"
    restart: always
    networks:
      - skynet
    environment:
      - ENV=${ENV}
      - VIRTUAL_HOST=${ENDPOINT}
      - LETSENCRYPT_HOST=${ENDPOINT}
      - VIRTUAL_PORT=8955
    volumes:
      - ./:/go/src/gitlab.com/InfoBlogFriends/server
networks:
  skynet:
    external:
      name: skynet