version: '3.3'
services:
  api:
    container_name: infoblogserver_${ENV}
    build: "."
    command: bash -c "go run ./cmd/server"
    restart: always
    networks:
      - skynet
    environment:
      - ENV=${ENV}
      - VIRTUAL_HOST=${ENDPOINT}
      - LETSENCRYPT_HOST=${ENDPOINT}
      - VIRTUAL_PORT=8955
    volumes:
      - /home/go:/go
      - ./:/go/src/gitlab.com/InfoBlogFriends/server
  mp4encoder:
    container_name: mp4encoder_${ENV}
    image: jlesage/handbrake
    restart: always
    networks:
      - skynet
    volumes:
      - ./public/videos/new:/watch:rw
      - ./public/videos/converted:/output:rw
  hlsencoder:
    container_name: hlsencoder_${ENV}
    image: ptflp/docker-ffmpeg-hls
    restart: always
    networks:
      - skynet
    volumes:
      - ./public/videos/tohls:/root/input
      - ./public/videos/hls:/root/output
networks:
  skynet:
    external:
      name: skynet