app:
  dev: true
  FrontEnd: "http://localhost:3000"

db:
  net: "tcp"
  driver: "mysql"
  dbname: "infoblog"
  username: "root"
  password: "jxtymCkj;ysGfhjkm"
  host: "157.245.249.1"
  timeout: 10

redis:
  host: "127.0.0.1"
  port: 6379

server:
  port: 8955