app:
  dev: true

db:
  net: "tcp"
  driver: "mysql"
  dbname: "infoblog"
  username: "root"
  password: "root"
  host: "127.0.0.1"
  timeout: 10

SMSC:
  login: "friends_club"
  pwd: "Ff*R#RV1Oxkk"

redis:
  host: "127.0.0.1"
  port: 6379

server:
  port: 8955