app:
  dev: true
  FrontEnd: "http://localhost:3000"

db:
  net: "tcp"
  driver: "mysql"
  dbname: "infoblog"
  username: "root"
  password: "jxtymCkj;ysGfhjkm"
  host: "infoblogdb"
  timeout: 10

Email:
  ServerAddress: "smtp.mail.ru"
  Port: "465"
  From: "friends@22byte.com"
  Login: "friends@22byte.com"
  Password: "ygTta2O)1pTH"

SMSC:
  login: "friends_club"
  pwd: "Ff*R#RV1Oxkk"
  cost: "3"
  fmt: "3"
  dev: false

redis:
  host: "infoblogredis"
  port: 6379

server:
  port: 8955

oauth2:
  google:
    clientID: "48097972269-g6jhrco7gii44i76j7trqseikb9d44ke.apps.googleusercontent.com"
    clientSecret: "6oBPBedmIwmFmiZvqkeCp2n_"
    redirectUrl: "https://3e7305205715.ngrok.io/auth/oauth2/google/callback"
  facebook:
    clientID: "536162860767446"
    clientSecret: "6f4846f480c96a7fe19ecb5824b71a18"
    redirectUrl: "https://3e7305205715.ngrok.io/auth/oauth2/facebook/callback"
