app:
  dev: false

db:
  net: "tcp"
  driver: "mysql"
  dbname: "infoblog"
  username: "root"
  password: "jxtymCkj;ysGfhjkm"
  host: "infoblogdb"
  timeout: 10

Email:
  ServerAddress: "smtp.mail.ru"
  Port: "465"
  From: "friends@22byte.com"
  Login: "friends@22byte.com"
  Password: "ygTta2O)1pTH"

SMSC:
  login: "friends_club"
  pwd: "Ff*R#RV1Oxkk"
  cost: "3"
  fmt: "3"
  dev: false

redis:
  host: "infoblogredis"
  port: 6379

server:
  port: 8955