app:
  dev: true
  FrontEnd: "http://localhost:3000"

db:
  net: "tcp"
  driver: "mysql"
  dbname: "infoblog"
  username: "root"
  password: "jxtymCkj;ysGfhjkm"
  host: "157.245.249.1"
  timeout: 10

server:
  port: 8955


SMSC:
  dev: true


oauth2:
  google:
    clientID: "48097972269-g6jhrco7gii44i76j7trqseikb9d44ke.apps.googleusercontent.com"
    clientSecret: "6oBPBedmIwmFmiZvqkeCp2n_"
    redirectUrl: "https://stageapi.ptflp.ru/auth/oauth2/google/callback"
  facebook:
    clientID: "536162860767446"
    clientSecret: "6f4846f480c96a7fe19ecb5824b71a18"
    redirectUrl: "https://stageapi.ptflp.ru/auth/oauth2/facebook/callback"